In [ ]:
conda install numpy

In [5]:
import numpy as np


In [6]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [8]:
type(arr)

numpy.ndarray

In [9]:
print(arr)

[1 2 3 4 5]


In [10]:
arr.shape

(5,)

In [11]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[9,7,6,8,9]

arr=np.array([l1,l2,l3])

In [12]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [17]:
arr.shape

(3, 5)

In [18]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [21]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
arr.shape

(3, 5)

In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [25]:
arr[3]

4

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
l3=[9,7,6,8,9]

arr=np.array([l1,l2,l3])

In [30]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [31]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [39]:
arr=np.arange(0,10)

In [40]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[3:]=100

In [42]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [43]:
arr=np.arange(0,10,2)

In [44]:
arr

array([0, 2, 4, 6, 8])

In [45]:
arr=np.linspace(0,10,50)

In [46]:
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [75]:
arr=np.arange(1,10)

In [76]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr1=arr

In [78]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [79]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [71]:
arr1=arr.copy()

In [80]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [81]:
val=2

arr<2

array([ True, False, False, False, False, False, False, False, False])

In [84]:
val=2

arr[arr<2]

array([1])

In [85]:
val=2

arr[arr<300]

array([1, 2, 3])

In [82]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [87]:
arr1=np.arange(0,10).reshape(2,5)

In [89]:
arr2=np.arange(0,10).reshape(2,5)

In [90]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [99]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [93]:
np.ones(4)

array([1., 1., 1., 1.])

In [95]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [98]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [96]:
np.random.rand(3,3)

array([[0.37594172, 0.7164333 , 0.44668641],
       [0.66351198, 0.54259827, 0.70029046],
       [0.26532342, 0.88313045, 0.17412069]])

In [100]:
arr_ex=np.random.randn(4,4)

In [101]:
arr_ex

array([[-1.13142428, -0.67612376,  0.98518071, -0.49587481],
       [-2.7954049 ,  0.00579648, -1.32206842, -1.7940017 ],
       [-1.19973097, -0.99270128,  0.85493508,  0.13893929],
       [-0.40965857,  0.76289067,  0.33349265,  0.38691854]])

In [109]:
np.random.randint(0,100,8).reshape(4,2)

array([[38, 29],
       [13,  3],
       [13, 59],
       [51, 28]])

In [102]:
np.random.random_sample((1,5))

array([[0.48931221, 0.91814488, 0.80012858, 0.21203105, 0.9258319 ]])